apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod
  labels:
    app: gpu-test
spec:
  volumes:
  - name: nvidia-driver
    hostPath:
      path: /usr/local/lib/nvidia
  containers:
  - name: tensorflow
    image: gcr.io/tensorflow/tensorflow:latest-gpu
    env:
    - name: LD_LIBRARY_PATH
      value: /usr/local/nvidia
    ports:
    - containerPort: 8888
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
    volumeMounts:
    - name: nvidia-driver
      mountPath: /usr/local/nvidia/
      readOnly: true
