apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  labels:
        role: nfs-server
spec:
  containers:
  - name: nfs-server
    image: gcr.io/google-samples/nfs-server:1.1
    ports:
      - name: nfs
        containerPort: 2049
      - name: mountd
        containerPort: 20048
      - name: rpcbind
        containerPort: 111
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /exports
        name: exports    
  volumes:
    - name: exports
      hostPath:
        path: /exports
  nodeSelector:
    node-role.kubernetes.io/master:
  tolerations: 
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server    
