kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-tensorflow-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      nfs: "tensorflow"